language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install codecov -g
  - npm install
  
after_success:
  - codecov

script:
  - npm run-script build

notifications:
  email:
    on_failure: change
